apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: admindb
  namespace: jwalkmedia
  labels:
    stage: production
    name: admindb
    app: jwmAdmin
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        stage: production
        name: graphql-server
        app: jwmAdmin
    spec:
      containers:
        - name: admindb
          image: jwm-admin-api:latest
          ports:
            - name: jwmAdmin-3000
              containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: admindb
  namespace: jwalkmedia
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    stage: production
    name: admindb
    app: jwmAdmin