apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: admindb
  namespace: jwalkmedia
  labels:
    stage: production
    name: admindb
    app: postgres
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        stage: production
        name: admindb
        app: postgres
    spec:
      containers:
        - name: postgres
          image: 'postgres:10.3'
          env:
            - name: POSTGRES_PASSWORD
              value: 'jwmAdmin'
            - name: POSTGRES_USER
              value: 'jwmAdmin'
          ports:
            - name: postgres-5432
              containerPort: 5432
          volumeMounts:
            - name: admindb-disk
              readOnly: false
              mountPath: /var/lib/postgresql
      restartPolicy: Always
      volumes:
        - name: admindb-disk
          persistentVolumeClaim:
            claimName: admindb-disk
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: admindb-disk
  namespace: jwalkmedia
  labels:
    stage: production
    name: admindb
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: Service
metadata:
  name: admindb
  namespace: jwalkmedia
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    stage: production
    name: admindb
    app: postgres